/**
 * This package contains classes which have the solutions from the tasks set by the forum https://ProjectEuler.net.
 **/
package projecteuler;

/**
 *
 * @author Jordan Atkinson jordan.atkinson3@gmail.com
 */
public class EvenFibonacciNumbers {

    /**
     * constructor which will call the method to complete task 3.
     * 
     * @param args command line arguments.
     */
    public static void main(String[] args) {
        
        System.out.println("Task 2 - Even Fibonacci Numbers\n"
                + "Each new term in the Fibonacci sequence is generated "
                + "by adding the previous two terms. By starting with 1 and 2, "
                + "the first 10 terms will be:\n"
                + "1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...\n"
                + "By considering the terms in the Fibonacci sequence whose "
                + "values do not exceed four million, find the sum of the "
                + "even-valued terms.");
        
        final int total = task2();
        System.out.println("" + total);
        
    }

    /**
     * Method used to complete Task 2 - Even Fibonacci Numbers.
     * 
     * Each new term in the Fibonacci sequence is generated by adding the 
     * previous two terms. By starting with 1 and 2, the first 10 terms will be:
     * 
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     * 
     * By considering the terms in the Fibonacci sequence whose values do not 
     * exceed four million, find the sum of the even-valued terms..
     * 
     * @return integer which is the total given after completing the above task.
     */
    private static int task2() {
        
        int sum = 0;
        int temp = 1; 
        int temp2 = 1;
        int tempTotal = 0;
         
        for (int i = tempTotal; tempTotal < 4000000; i += tempTotal) {
             tempTotal = temp + temp2;
             if ((tempTotal % 2) == 0) {
                 sum += tempTotal;
             }
             temp = temp2;
             temp2 = tempTotal;
        }
        return sum;
    }
}
